apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: cattle-gatekeeper-system
spec:
  match:
    - excludedNamespaces: ["kube-system", "default"]
      processes: ["*"]